repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

default_language_version:
    python: python3.8

default_stages: [push]
