version: '3'
services:
  database:
    container_name: database
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
