version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"

  database:
    container_name: database
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
